# Datei: config/rbac/clusterrole_binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-operator-deployments-rolebinding
subjects:
- kind: ServiceAccount
  name: traefik-operator-1-controller-manager
  namespace: traefik-operator-1-system
roleRef:
  kind: ClusterRole
  name: traefik-operator-deployments-role
  apiGroup: rbac.authorization.k8s.io