---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - traefik.mh.edu.com
  resources:
  - traefikinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - traefik.mh.edu.com
  resources:
  - traefikinstances/finalizers
  verbs:
  - update
- apiGroups:
  - traefik.mh.edu.com
  resources:
  - traefikinstances/status
  verbs:
  - get
  - patch
  - update
